//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajjHachathon.Tarie.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public string DeviceId { get; set; }
        public string Longitude { get; set; }
        public string Latidude { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string Resolution { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<bool> Resolved { get; set; }
        public string ResolutionDate { get; set; }
        public Nullable<System.DateTime> CaseDate { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
